### ISSUE TITLE
Finalizing Schedule for Data Science Bootcamp @ 2017

### ISSUE THREAD

**Issue by aritrasep** [INFORMS-Students-Chapter-USF/DataScienceBootCamp-2017#1]
@danielhromero @vigneshs3587 @yanwang2 @SakibUSF please mention your thoughts, concerns and modification on the schedule for Data Science Bootcamp @ 2017 in this thread.

**Comment by vigneshs3587** [comment]
@aritrasep Great! Overall structure looks good. But, I have one concern, we have to target all age groups (freshmen, junior level, and senior level). Whatever you have proposed is a high level. Let's have a meeting with everyone (in this group) in person to know their views. Please suggest us time and date.

**Comment by aritrasep** [comment]
@danielhromero @vigneshs3587 @yanwang2 @SakibUSF I will be in school today from 3:00 - 6:00 PM. If  any of guys are available we can meet during this time period.
